package com.llsfw.demo.mapper.standard.demo;

import com.llsfw.demo.model.standard.demo.TtDbsDemo;
import com.llsfw.demo.model.standard.demo.TtDbsDemoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtDbsDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int countByExample(TtDbsDemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int deleteByExample(TtDbsDemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int deleteByPrimaryKey(String demoCol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int insert(TtDbsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int insertSelective(TtDbsDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    List<TtDbsDemo> selectByExample(TtDbsDemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TtDbsDemo record, @Param("example") TtDbsDemoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    int updateByExample(@Param("record") TtDbsDemo record, @Param("example") TtDbsDemoCriteria example);
}