package com.llsfw.generator.model.standard.system;

import java.io.Serializable;
import java.util.Date;

public class TtDynamicDataSource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_DRIVER_CLASS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsDriverClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_URL
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_USER_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_PASSWORD
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.DBS_STATUS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String dbsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.CREATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.CREATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_NAME
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsName() {
        return dbsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_NAME
     *
     * @param dbsName the value for TT_DYNAMIC_DATA_SOURCE.DBS_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsName(String dbsName) {
        this.dbsName = dbsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_DRIVER_CLASS
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_DRIVER_CLASS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsDriverClass() {
        return dbsDriverClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_DRIVER_CLASS
     *
     * @param dbsDriverClass the value for TT_DYNAMIC_DATA_SOURCE.DBS_DRIVER_CLASS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsDriverClass(String dbsDriverClass) {
        this.dbsDriverClass = dbsDriverClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_URL
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_URL
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsUrl() {
        return dbsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_URL
     *
     * @param dbsUrl the value for TT_DYNAMIC_DATA_SOURCE.DBS_URL
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsUrl(String dbsUrl) {
        this.dbsUrl = dbsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_USER_NAME
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_USER_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsUserName() {
        return dbsUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_USER_NAME
     *
     * @param dbsUserName the value for TT_DYNAMIC_DATA_SOURCE.DBS_USER_NAME
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsUserName(String dbsUserName) {
        this.dbsUserName = dbsUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_PASSWORD
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_PASSWORD
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsPassword() {
        return dbsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_PASSWORD
     *
     * @param dbsPassword the value for TT_DYNAMIC_DATA_SOURCE.DBS_PASSWORD
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsPassword(String dbsPassword) {
        this.dbsPassword = dbsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_STATUS
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.DBS_STATUS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getDbsStatus() {
        return dbsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.DBS_STATUS
     *
     * @param dbsStatus the value for TT_DYNAMIC_DATA_SOURCE.DBS_STATUS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDbsStatus(String dbsStatus) {
        this.dbsStatus = dbsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.CREATE_BY
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.CREATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.CREATE_BY
     *
     * @param createBy the value for TT_DYNAMIC_DATA_SOURCE.CREATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.CREATE_DATE
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.CREATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.CREATE_DATE
     *
     * @param createDate the value for TT_DYNAMIC_DATA_SOURCE.CREATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_BY
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.UPDATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_BY
     *
     * @param updateBy the value for TT_DYNAMIC_DATA_SOURCE.UPDATE_BY
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_DATE
     *
     * @return the value of TT_DYNAMIC_DATA_SOURCE.UPDATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DYNAMIC_DATA_SOURCE.UPDATE_DATE
     *
     * @param updateDate the value for TT_DYNAMIC_DATA_SOURCE.UPDATE_DATE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtDynamicDataSource other = (TtDynamicDataSource) that;
        return (this.getDbsName() == null ? other.getDbsName() == null : this.getDbsName().equals(other.getDbsName()))
            && (this.getDbsDriverClass() == null ? other.getDbsDriverClass() == null : this.getDbsDriverClass().equals(other.getDbsDriverClass()))
            && (this.getDbsUrl() == null ? other.getDbsUrl() == null : this.getDbsUrl().equals(other.getDbsUrl()))
            && (this.getDbsUserName() == null ? other.getDbsUserName() == null : this.getDbsUserName().equals(other.getDbsUserName()))
            && (this.getDbsPassword() == null ? other.getDbsPassword() == null : this.getDbsPassword().equals(other.getDbsPassword()))
            && (this.getDbsStatus() == null ? other.getDbsStatus() == null : this.getDbsStatus().equals(other.getDbsStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDbsName() == null) ? 0 : getDbsName().hashCode());
        result = prime * result + ((getDbsDriverClass() == null) ? 0 : getDbsDriverClass().hashCode());
        result = prime * result + ((getDbsUrl() == null) ? 0 : getDbsUrl().hashCode());
        result = prime * result + ((getDbsUserName() == null) ? 0 : getDbsUserName().hashCode());
        result = prime * result + ((getDbsPassword() == null) ? 0 : getDbsPassword().hashCode());
        result = prime * result + ((getDbsStatus() == null) ? 0 : getDbsStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}