package com.llsfw.generator.model.standard.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TtDynamicDataSourceCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public TtDynamicDataSourceCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDbsNameIsNull() {
            addCriterion("DBS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbsNameIsNotNull() {
            addCriterion("DBS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbsNameEqualTo(String value) {
            addCriterion("DBS_NAME =", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameNotEqualTo(String value) {
            addCriterion("DBS_NAME <>", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameGreaterThan(String value) {
            addCriterion("DBS_NAME >", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_NAME >=", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameLessThan(String value) {
            addCriterion("DBS_NAME <", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameLessThanOrEqualTo(String value) {
            addCriterion("DBS_NAME <=", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameLike(String value) {
            addCriterion("DBS_NAME like", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameNotLike(String value) {
            addCriterion("DBS_NAME not like", value, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameIn(List<String> values) {
            addCriterion("DBS_NAME in", values, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameNotIn(List<String> values) {
            addCriterion("DBS_NAME not in", values, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameBetween(String value1, String value2) {
            addCriterion("DBS_NAME between", value1, value2, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsNameNotBetween(String value1, String value2) {
            addCriterion("DBS_NAME not between", value1, value2, "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassIsNull() {
            addCriterion("DBS_DRIVER_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassIsNotNull() {
            addCriterion("DBS_DRIVER_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassEqualTo(String value) {
            addCriterion("DBS_DRIVER_CLASS =", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassNotEqualTo(String value) {
            addCriterion("DBS_DRIVER_CLASS <>", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassGreaterThan(String value) {
            addCriterion("DBS_DRIVER_CLASS >", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_DRIVER_CLASS >=", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassLessThan(String value) {
            addCriterion("DBS_DRIVER_CLASS <", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassLessThanOrEqualTo(String value) {
            addCriterion("DBS_DRIVER_CLASS <=", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassLike(String value) {
            addCriterion("DBS_DRIVER_CLASS like", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassNotLike(String value) {
            addCriterion("DBS_DRIVER_CLASS not like", value, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassIn(List<String> values) {
            addCriterion("DBS_DRIVER_CLASS in", values, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassNotIn(List<String> values) {
            addCriterion("DBS_DRIVER_CLASS not in", values, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassBetween(String value1, String value2) {
            addCriterion("DBS_DRIVER_CLASS between", value1, value2, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassNotBetween(String value1, String value2) {
            addCriterion("DBS_DRIVER_CLASS not between", value1, value2, "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsUrlIsNull() {
            addCriterion("DBS_URL is null");
            return (Criteria) this;
        }

        public Criteria andDbsUrlIsNotNull() {
            addCriterion("DBS_URL is not null");
            return (Criteria) this;
        }

        public Criteria andDbsUrlEqualTo(String value) {
            addCriterion("DBS_URL =", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlNotEqualTo(String value) {
            addCriterion("DBS_URL <>", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlGreaterThan(String value) {
            addCriterion("DBS_URL >", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_URL >=", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlLessThan(String value) {
            addCriterion("DBS_URL <", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlLessThanOrEqualTo(String value) {
            addCriterion("DBS_URL <=", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlLike(String value) {
            addCriterion("DBS_URL like", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlNotLike(String value) {
            addCriterion("DBS_URL not like", value, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlIn(List<String> values) {
            addCriterion("DBS_URL in", values, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlNotIn(List<String> values) {
            addCriterion("DBS_URL not in", values, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlBetween(String value1, String value2) {
            addCriterion("DBS_URL between", value1, value2, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUrlNotBetween(String value1, String value2) {
            addCriterion("DBS_URL not between", value1, value2, "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameIsNull() {
            addCriterion("DBS_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameIsNotNull() {
            addCriterion("DBS_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameEqualTo(String value) {
            addCriterion("DBS_USER_NAME =", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameNotEqualTo(String value) {
            addCriterion("DBS_USER_NAME <>", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameGreaterThan(String value) {
            addCriterion("DBS_USER_NAME >", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_USER_NAME >=", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameLessThan(String value) {
            addCriterion("DBS_USER_NAME <", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameLessThanOrEqualTo(String value) {
            addCriterion("DBS_USER_NAME <=", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameLike(String value) {
            addCriterion("DBS_USER_NAME like", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameNotLike(String value) {
            addCriterion("DBS_USER_NAME not like", value, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameIn(List<String> values) {
            addCriterion("DBS_USER_NAME in", values, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameNotIn(List<String> values) {
            addCriterion("DBS_USER_NAME not in", values, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameBetween(String value1, String value2) {
            addCriterion("DBS_USER_NAME between", value1, value2, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameNotBetween(String value1, String value2) {
            addCriterion("DBS_USER_NAME not between", value1, value2, "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordIsNull() {
            addCriterion("DBS_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordIsNotNull() {
            addCriterion("DBS_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordEqualTo(String value) {
            addCriterion("DBS_PASSWORD =", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordNotEqualTo(String value) {
            addCriterion("DBS_PASSWORD <>", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordGreaterThan(String value) {
            addCriterion("DBS_PASSWORD >", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_PASSWORD >=", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordLessThan(String value) {
            addCriterion("DBS_PASSWORD <", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordLessThanOrEqualTo(String value) {
            addCriterion("DBS_PASSWORD <=", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordLike(String value) {
            addCriterion("DBS_PASSWORD like", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordNotLike(String value) {
            addCriterion("DBS_PASSWORD not like", value, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordIn(List<String> values) {
            addCriterion("DBS_PASSWORD in", values, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordNotIn(List<String> values) {
            addCriterion("DBS_PASSWORD not in", values, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordBetween(String value1, String value2) {
            addCriterion("DBS_PASSWORD between", value1, value2, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordNotBetween(String value1, String value2) {
            addCriterion("DBS_PASSWORD not between", value1, value2, "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsStatusIsNull() {
            addCriterion("DBS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andDbsStatusIsNotNull() {
            addCriterion("DBS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andDbsStatusEqualTo(String value) {
            addCriterion("DBS_STATUS =", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusNotEqualTo(String value) {
            addCriterion("DBS_STATUS <>", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusGreaterThan(String value) {
            addCriterion("DBS_STATUS >", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusGreaterThanOrEqualTo(String value) {
            addCriterion("DBS_STATUS >=", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusLessThan(String value) {
            addCriterion("DBS_STATUS <", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusLessThanOrEqualTo(String value) {
            addCriterion("DBS_STATUS <=", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusLike(String value) {
            addCriterion("DBS_STATUS like", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusNotLike(String value) {
            addCriterion("DBS_STATUS not like", value, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusIn(List<String> values) {
            addCriterion("DBS_STATUS in", values, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusNotIn(List<String> values) {
            addCriterion("DBS_STATUS not in", values, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusBetween(String value1, String value2) {
            addCriterion("DBS_STATUS between", value1, value2, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andDbsStatusNotBetween(String value1, String value2) {
            addCriterion("DBS_STATUS not between", value1, value2, "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDbsNameLikeInsensitive(String value) {
            addCriterion("upper(DBS_NAME) like", value.toUpperCase(), "dbsName");
            return (Criteria) this;
        }

        public Criteria andDbsDriverClassLikeInsensitive(String value) {
            addCriterion("upper(DBS_DRIVER_CLASS) like", value.toUpperCase(), "dbsDriverClass");
            return (Criteria) this;
        }

        public Criteria andDbsUrlLikeInsensitive(String value) {
            addCriterion("upper(DBS_URL) like", value.toUpperCase(), "dbsUrl");
            return (Criteria) this;
        }

        public Criteria andDbsUserNameLikeInsensitive(String value) {
            addCriterion("upper(DBS_USER_NAME) like", value.toUpperCase(), "dbsUserName");
            return (Criteria) this;
        }

        public Criteria andDbsPasswordLikeInsensitive(String value) {
            addCriterion("upper(DBS_PASSWORD) like", value.toUpperCase(), "dbsPassword");
            return (Criteria) this;
        }

        public Criteria andDbsStatusLikeInsensitive(String value) {
            addCriterion("upper(DBS_STATUS) like", value.toUpperCase(), "dbsStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 07 22:45:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}