package com.llsfw.generator.model.standard.system;

import java.io.Serializable;
import java.util.Date;

public class TtRequestResponseLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REQUEST_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.BEGIN_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.END_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REQUEST_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.LOGIN_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.SESSION_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.SCHEME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String scheme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.SERVER_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.SERVER_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long serverPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String requestUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.METHOD
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REQUEST_PARAMS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String requestParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.MOBILE_PAT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Short mobilePat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.AUTH_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String authType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.CHARACTER_ENCODING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String characterEncoding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.CONTENT_LENGTH
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long contentLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String headerNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.LOCAL_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String localAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.LOCAL_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String localName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.LOCAL_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long localPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.PATH_TRANSLATED
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String pathTranslated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.PROTOCOL
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String remoteAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REMOTE_HOST
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String remoteHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REMOTE_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long remotePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REMOTE_USER
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String remoteUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.REQUESTED_SESSION_ID_VALID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Short requestedSessionIdValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.SECURE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Short secure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String responseHeaderNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CHARACTER_ENCONDING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String responseCharacterEnconding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String responseContentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_STATUS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long responseStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_VIEW
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String responseView;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_CLASS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String exceptionClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_MESSAGE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String exceptionMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_STACK_TRACK
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private String exceptionStackTrack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.JVM_MAX_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long jvmMaxMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long jvmTotalMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.JVM_FREE_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long jvmFreeMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.JVM_USER_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Long jvmUserMemory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_REQUEST_RESPONSE_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_ID
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REQUEST_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_ID
     *
     * @param requestId the value for TT_REQUEST_RESPONSE_LOG.REQUEST_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.BEGIN_TIME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.BEGIN_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.BEGIN_TIME
     *
     * @param beginTime the value for TT_REQUEST_RESPONSE_LOG.BEGIN_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.END_TIME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.END_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.END_TIME
     *
     * @param endTime the value for TT_REQUEST_RESPONSE_LOG.END_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_TIME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REQUEST_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_TIME
     *
     * @param requestTime the value for TT_REQUEST_RESPONSE_LOG.REQUEST_TIME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRequestTime(Long requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.LOGIN_NAME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.LOGIN_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.LOGIN_NAME
     *
     * @param loginName the value for TT_REQUEST_RESPONSE_LOG.LOGIN_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.SESSION_ID
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.SESSION_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.SESSION_ID
     *
     * @param sessionId the value for TT_REQUEST_RESPONSE_LOG.SESSION_ID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.SCHEME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.SCHEME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.SCHEME
     *
     * @param scheme the value for TT_REQUEST_RESPONSE_LOG.SCHEME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.SERVER_NAME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.SERVER_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.SERVER_NAME
     *
     * @param serverName the value for TT_REQUEST_RESPONSE_LOG.SERVER_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.SERVER_PORT
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.SERVER_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.SERVER_PORT
     *
     * @param serverPort the value for TT_REQUEST_RESPONSE_LOG.SERVER_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setServerPort(Long serverPort) {
        this.serverPort = serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_URI
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_URI
     *
     * @param requestUri the value for TT_REQUEST_RESPONSE_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.METHOD
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.METHOD
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.METHOD
     *
     * @param method the value for TT_REQUEST_RESPONSE_LOG.METHOD
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_PARAMS
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REQUEST_PARAMS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REQUEST_PARAMS
     *
     * @param requestParams the value for TT_REQUEST_RESPONSE_LOG.REQUEST_PARAMS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.MOBILE_PAT
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.MOBILE_PAT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Short getMobilePat() {
        return mobilePat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.MOBILE_PAT
     *
     * @param mobilePat the value for TT_REQUEST_RESPONSE_LOG.MOBILE_PAT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setMobilePat(Short mobilePat) {
        this.mobilePat = mobilePat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.AUTH_TYPE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.AUTH_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.AUTH_TYPE
     *
     * @param authType the value for TT_REQUEST_RESPONSE_LOG.AUTH_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.CHARACTER_ENCODING
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.CHARACTER_ENCODING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getCharacterEncoding() {
        return characterEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.CHARACTER_ENCODING
     *
     * @param characterEncoding the value for TT_REQUEST_RESPONSE_LOG.CHARACTER_ENCODING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setCharacterEncoding(String characterEncoding) {
        this.characterEncoding = characterEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.CONTENT_LENGTH
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.CONTENT_LENGTH
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getContentLength() {
        return contentLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.CONTENT_LENGTH
     *
     * @param contentLength the value for TT_REQUEST_RESPONSE_LOG.CONTENT_LENGTH
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setContentLength(Long contentLength) {
        this.contentLength = contentLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.CONTENT_TYPE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.CONTENT_TYPE
     *
     * @param contentType the value for TT_REQUEST_RESPONSE_LOG.CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.HEADER_NAMES
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getHeaderNames() {
        return headerNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.HEADER_NAMES
     *
     * @param headerNames the value for TT_REQUEST_RESPONSE_LOG.HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setHeaderNames(String headerNames) {
        this.headerNames = headerNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_ADDR
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.LOCAL_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getLocalAddr() {
        return localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_ADDR
     *
     * @param localAddr the value for TT_REQUEST_RESPONSE_LOG.LOCAL_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setLocalAddr(String localAddr) {
        this.localAddr = localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_NAME
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.LOCAL_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getLocalName() {
        return localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_NAME
     *
     * @param localName the value for TT_REQUEST_RESPONSE_LOG.LOCAL_NAME
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setLocalName(String localName) {
        this.localName = localName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_PORT
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.LOCAL_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getLocalPort() {
        return localPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.LOCAL_PORT
     *
     * @param localPort the value for TT_REQUEST_RESPONSE_LOG.LOCAL_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setLocalPort(Long localPort) {
        this.localPort = localPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.PATH_TRANSLATED
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.PATH_TRANSLATED
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getPathTranslated() {
        return pathTranslated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.PATH_TRANSLATED
     *
     * @param pathTranslated the value for TT_REQUEST_RESPONSE_LOG.PATH_TRANSLATED
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setPathTranslated(String pathTranslated) {
        this.pathTranslated = pathTranslated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.PROTOCOL
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.PROTOCOL
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.PROTOCOL
     *
     * @param protocol the value for TT_REQUEST_RESPONSE_LOG.PROTOCOL
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_ADDR
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_ADDR
     *
     * @param remoteAddr the value for TT_REQUEST_RESPONSE_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_HOST
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REMOTE_HOST
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRemoteHost() {
        return remoteHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_HOST
     *
     * @param remoteHost the value for TT_REQUEST_RESPONSE_LOG.REMOTE_HOST
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRemoteHost(String remoteHost) {
        this.remoteHost = remoteHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_PORT
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REMOTE_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getRemotePort() {
        return remotePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_PORT
     *
     * @param remotePort the value for TT_REQUEST_RESPONSE_LOG.REMOTE_PORT
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRemotePort(Long remotePort) {
        this.remotePort = remotePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_USER
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REMOTE_USER
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getRemoteUser() {
        return remoteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REMOTE_USER
     *
     * @param remoteUser the value for TT_REQUEST_RESPONSE_LOG.REMOTE_USER
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRemoteUser(String remoteUser) {
        this.remoteUser = remoteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.REQUESTED_SESSION_ID_VALID
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.REQUESTED_SESSION_ID_VALID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Short getRequestedSessionIdValid() {
        return requestedSessionIdValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.REQUESTED_SESSION_ID_VALID
     *
     * @param requestedSessionIdValid the value for TT_REQUEST_RESPONSE_LOG.REQUESTED_SESSION_ID_VALID
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setRequestedSessionIdValid(Short requestedSessionIdValid) {
        this.requestedSessionIdValid = requestedSessionIdValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.SECURE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.SECURE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Short getSecure() {
        return secure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.SECURE
     *
     * @param secure the value for TT_REQUEST_RESPONSE_LOG.SECURE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setSecure(Short secure) {
        this.secure = secure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_HEADER_NAMES
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.RESPONSE_HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getResponseHeaderNames() {
        return responseHeaderNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_HEADER_NAMES
     *
     * @param responseHeaderNames the value for TT_REQUEST_RESPONSE_LOG.RESPONSE_HEADER_NAMES
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setResponseHeaderNames(String responseHeaderNames) {
        this.responseHeaderNames = responseHeaderNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CHARACTER_ENCONDING
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.RESPONSE_CHARACTER_ENCONDING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getResponseCharacterEnconding() {
        return responseCharacterEnconding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CHARACTER_ENCONDING
     *
     * @param responseCharacterEnconding the value for TT_REQUEST_RESPONSE_LOG.RESPONSE_CHARACTER_ENCONDING
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setResponseCharacterEnconding(String responseCharacterEnconding) {
        this.responseCharacterEnconding = responseCharacterEnconding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CONTENT_TYPE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.RESPONSE_CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getResponseContentType() {
        return responseContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_CONTENT_TYPE
     *
     * @param responseContentType the value for TT_REQUEST_RESPONSE_LOG.RESPONSE_CONTENT_TYPE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setResponseContentType(String responseContentType) {
        this.responseContentType = responseContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_STATUS
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.RESPONSE_STATUS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getResponseStatus() {
        return responseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_STATUS
     *
     * @param responseStatus the value for TT_REQUEST_RESPONSE_LOG.RESPONSE_STATUS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setResponseStatus(Long responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_VIEW
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.RESPONSE_VIEW
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getResponseView() {
        return responseView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.RESPONSE_VIEW
     *
     * @param responseView the value for TT_REQUEST_RESPONSE_LOG.RESPONSE_VIEW
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setResponseView(String responseView) {
        this.responseView = responseView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_CLASS
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.EXCEPTION_CLASS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getExceptionClass() {
        return exceptionClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_CLASS
     *
     * @param exceptionClass the value for TT_REQUEST_RESPONSE_LOG.EXCEPTION_CLASS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setExceptionClass(String exceptionClass) {
        this.exceptionClass = exceptionClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_MESSAGE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.EXCEPTION_MESSAGE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getExceptionMessage() {
        return exceptionMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_MESSAGE
     *
     * @param exceptionMessage the value for TT_REQUEST_RESPONSE_LOG.EXCEPTION_MESSAGE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setExceptionMessage(String exceptionMessage) {
        this.exceptionMessage = exceptionMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_STACK_TRACK
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.EXCEPTION_STACK_TRACK
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public String getExceptionStackTrack() {
        return exceptionStackTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.EXCEPTION_STACK_TRACK
     *
     * @param exceptionStackTrack the value for TT_REQUEST_RESPONSE_LOG.EXCEPTION_STACK_TRACK
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setExceptionStackTrack(String exceptionStackTrack) {
        this.exceptionStackTrack = exceptionStackTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_MAX_MEMORY
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.JVM_MAX_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getJvmMaxMemory() {
        return jvmMaxMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_MAX_MEMORY
     *
     * @param jvmMaxMemory the value for TT_REQUEST_RESPONSE_LOG.JVM_MAX_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setJvmMaxMemory(Long jvmMaxMemory) {
        this.jvmMaxMemory = jvmMaxMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_TOTAL_MEMORY
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getJvmTotalMemory() {
        return jvmTotalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_TOTAL_MEMORY
     *
     * @param jvmTotalMemory the value for TT_REQUEST_RESPONSE_LOG.JVM_TOTAL_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setJvmTotalMemory(Long jvmTotalMemory) {
        this.jvmTotalMemory = jvmTotalMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_FREE_MEMORY
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.JVM_FREE_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getJvmFreeMemory() {
        return jvmFreeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_FREE_MEMORY
     *
     * @param jvmFreeMemory the value for TT_REQUEST_RESPONSE_LOG.JVM_FREE_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setJvmFreeMemory(Long jvmFreeMemory) {
        this.jvmFreeMemory = jvmFreeMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_USER_MEMORY
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.JVM_USER_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Long getJvmUserMemory() {
        return jvmUserMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.JVM_USER_MEMORY
     *
     * @param jvmUserMemory the value for TT_REQUEST_RESPONSE_LOG.JVM_USER_MEMORY
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setJvmUserMemory(Long jvmUserMemory) {
        this.jvmUserMemory = jvmUserMemory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_REQUEST_RESPONSE_LOG.CREATE_DATE
     *
     * @return the value of TT_REQUEST_RESPONSE_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_REQUEST_RESPONSE_LOG.CREATE_DATE
     *
     * @param createDate the value for TT_REQUEST_RESPONSE_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtRequestResponseLog other = (TtRequestResponseLog) that;
        return (this.getRequestId() == null ? other.getRequestId() == null : this.getRequestId().equals(other.getRequestId()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getRequestTime() == null ? other.getRequestTime() == null : this.getRequestTime().equals(other.getRequestTime()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getSessionId() == null ? other.getSessionId() == null : this.getSessionId().equals(other.getSessionId()))
            && (this.getScheme() == null ? other.getScheme() == null : this.getScheme().equals(other.getScheme()))
            && (this.getServerName() == null ? other.getServerName() == null : this.getServerName().equals(other.getServerName()))
            && (this.getServerPort() == null ? other.getServerPort() == null : this.getServerPort().equals(other.getServerPort()))
            && (this.getRequestUri() == null ? other.getRequestUri() == null : this.getRequestUri().equals(other.getRequestUri()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getRequestParams() == null ? other.getRequestParams() == null : this.getRequestParams().equals(other.getRequestParams()))
            && (this.getMobilePat() == null ? other.getMobilePat() == null : this.getMobilePat().equals(other.getMobilePat()))
            && (this.getAuthType() == null ? other.getAuthType() == null : this.getAuthType().equals(other.getAuthType()))
            && (this.getCharacterEncoding() == null ? other.getCharacterEncoding() == null : this.getCharacterEncoding().equals(other.getCharacterEncoding()))
            && (this.getContentLength() == null ? other.getContentLength() == null : this.getContentLength().equals(other.getContentLength()))
            && (this.getContentType() == null ? other.getContentType() == null : this.getContentType().equals(other.getContentType()))
            && (this.getHeaderNames() == null ? other.getHeaderNames() == null : this.getHeaderNames().equals(other.getHeaderNames()))
            && (this.getLocalAddr() == null ? other.getLocalAddr() == null : this.getLocalAddr().equals(other.getLocalAddr()))
            && (this.getLocalName() == null ? other.getLocalName() == null : this.getLocalName().equals(other.getLocalName()))
            && (this.getLocalPort() == null ? other.getLocalPort() == null : this.getLocalPort().equals(other.getLocalPort()))
            && (this.getPathTranslated() == null ? other.getPathTranslated() == null : this.getPathTranslated().equals(other.getPathTranslated()))
            && (this.getProtocol() == null ? other.getProtocol() == null : this.getProtocol().equals(other.getProtocol()))
            && (this.getRemoteAddr() == null ? other.getRemoteAddr() == null : this.getRemoteAddr().equals(other.getRemoteAddr()))
            && (this.getRemoteHost() == null ? other.getRemoteHost() == null : this.getRemoteHost().equals(other.getRemoteHost()))
            && (this.getRemotePort() == null ? other.getRemotePort() == null : this.getRemotePort().equals(other.getRemotePort()))
            && (this.getRemoteUser() == null ? other.getRemoteUser() == null : this.getRemoteUser().equals(other.getRemoteUser()))
            && (this.getRequestedSessionIdValid() == null ? other.getRequestedSessionIdValid() == null : this.getRequestedSessionIdValid().equals(other.getRequestedSessionIdValid()))
            && (this.getSecure() == null ? other.getSecure() == null : this.getSecure().equals(other.getSecure()))
            && (this.getResponseHeaderNames() == null ? other.getResponseHeaderNames() == null : this.getResponseHeaderNames().equals(other.getResponseHeaderNames()))
            && (this.getResponseCharacterEnconding() == null ? other.getResponseCharacterEnconding() == null : this.getResponseCharacterEnconding().equals(other.getResponseCharacterEnconding()))
            && (this.getResponseContentType() == null ? other.getResponseContentType() == null : this.getResponseContentType().equals(other.getResponseContentType()))
            && (this.getResponseStatus() == null ? other.getResponseStatus() == null : this.getResponseStatus().equals(other.getResponseStatus()))
            && (this.getResponseView() == null ? other.getResponseView() == null : this.getResponseView().equals(other.getResponseView()))
            && (this.getExceptionClass() == null ? other.getExceptionClass() == null : this.getExceptionClass().equals(other.getExceptionClass()))
            && (this.getExceptionMessage() == null ? other.getExceptionMessage() == null : this.getExceptionMessage().equals(other.getExceptionMessage()))
            && (this.getExceptionStackTrack() == null ? other.getExceptionStackTrack() == null : this.getExceptionStackTrack().equals(other.getExceptionStackTrack()))
            && (this.getJvmMaxMemory() == null ? other.getJvmMaxMemory() == null : this.getJvmMaxMemory().equals(other.getJvmMaxMemory()))
            && (this.getJvmTotalMemory() == null ? other.getJvmTotalMemory() == null : this.getJvmTotalMemory().equals(other.getJvmTotalMemory()))
            && (this.getJvmFreeMemory() == null ? other.getJvmFreeMemory() == null : this.getJvmFreeMemory().equals(other.getJvmFreeMemory()))
            && (this.getJvmUserMemory() == null ? other.getJvmUserMemory() == null : this.getJvmUserMemory().equals(other.getJvmUserMemory()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRequestId() == null) ? 0 : getRequestId().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getRequestTime() == null) ? 0 : getRequestTime().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getSessionId() == null) ? 0 : getSessionId().hashCode());
        result = prime * result + ((getScheme() == null) ? 0 : getScheme().hashCode());
        result = prime * result + ((getServerName() == null) ? 0 : getServerName().hashCode());
        result = prime * result + ((getServerPort() == null) ? 0 : getServerPort().hashCode());
        result = prime * result + ((getRequestUri() == null) ? 0 : getRequestUri().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getRequestParams() == null) ? 0 : getRequestParams().hashCode());
        result = prime * result + ((getMobilePat() == null) ? 0 : getMobilePat().hashCode());
        result = prime * result + ((getAuthType() == null) ? 0 : getAuthType().hashCode());
        result = prime * result + ((getCharacterEncoding() == null) ? 0 : getCharacterEncoding().hashCode());
        result = prime * result + ((getContentLength() == null) ? 0 : getContentLength().hashCode());
        result = prime * result + ((getContentType() == null) ? 0 : getContentType().hashCode());
        result = prime * result + ((getHeaderNames() == null) ? 0 : getHeaderNames().hashCode());
        result = prime * result + ((getLocalAddr() == null) ? 0 : getLocalAddr().hashCode());
        result = prime * result + ((getLocalName() == null) ? 0 : getLocalName().hashCode());
        result = prime * result + ((getLocalPort() == null) ? 0 : getLocalPort().hashCode());
        result = prime * result + ((getPathTranslated() == null) ? 0 : getPathTranslated().hashCode());
        result = prime * result + ((getProtocol() == null) ? 0 : getProtocol().hashCode());
        result = prime * result + ((getRemoteAddr() == null) ? 0 : getRemoteAddr().hashCode());
        result = prime * result + ((getRemoteHost() == null) ? 0 : getRemoteHost().hashCode());
        result = prime * result + ((getRemotePort() == null) ? 0 : getRemotePort().hashCode());
        result = prime * result + ((getRemoteUser() == null) ? 0 : getRemoteUser().hashCode());
        result = prime * result + ((getRequestedSessionIdValid() == null) ? 0 : getRequestedSessionIdValid().hashCode());
        result = prime * result + ((getSecure() == null) ? 0 : getSecure().hashCode());
        result = prime * result + ((getResponseHeaderNames() == null) ? 0 : getResponseHeaderNames().hashCode());
        result = prime * result + ((getResponseCharacterEnconding() == null) ? 0 : getResponseCharacterEnconding().hashCode());
        result = prime * result + ((getResponseContentType() == null) ? 0 : getResponseContentType().hashCode());
        result = prime * result + ((getResponseStatus() == null) ? 0 : getResponseStatus().hashCode());
        result = prime * result + ((getResponseView() == null) ? 0 : getResponseView().hashCode());
        result = prime * result + ((getExceptionClass() == null) ? 0 : getExceptionClass().hashCode());
        result = prime * result + ((getExceptionMessage() == null) ? 0 : getExceptionMessage().hashCode());
        result = prime * result + ((getExceptionStackTrack() == null) ? 0 : getExceptionStackTrack().hashCode());
        result = prime * result + ((getJvmMaxMemory() == null) ? 0 : getJvmMaxMemory().hashCode());
        result = prime * result + ((getJvmTotalMemory() == null) ? 0 : getJvmTotalMemory().hashCode());
        result = prime * result + ((getJvmFreeMemory() == null) ? 0 : getJvmFreeMemory().hashCode());
        result = prime * result + ((getJvmUserMemory() == null) ? 0 : getJvmUserMemory().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }
}