package com.llsfw.demo.model.standard.demo;

import java.io.Serializable;

public class TtDbsDemo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_DBS_DEMO.DEMO_COL
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    private String demoCol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_DBS_DEMO.DEMO_COL
     *
     * @return the value of TT_DBS_DEMO.DEMO_COL
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    public String getDemoCol() {
        return demoCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_DBS_DEMO.DEMO_COL
     *
     * @param demoCol the value for TT_DBS_DEMO.DEMO_COL
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    public void setDemoCol(String demoCol) {
        this.demoCol = demoCol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtDbsDemo other = (TtDbsDemo) that;
        return (this.getDemoCol() == null ? other.getDemoCol() == null : this.getDemoCol().equals(other.getDemoCol()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DBS_DEMO
     *
     * @mbggenerated Sun Dec 06 00:03:33 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDemoCol() == null) ? 0 : getDemoCol().hashCode());
        return result;
    }
}