package com.llsfw.generator.mapper.standard.system;

import com.llsfw.generator.model.standard.system.TtDynamicDataSource;
import com.llsfw.generator.model.standard.system.TtDynamicDataSourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtDynamicDataSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int countByExample(TtDynamicDataSourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByExample(TtDynamicDataSourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByPrimaryKey(String dbsName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insert(TtDynamicDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insertSelective(TtDynamicDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    List<TtDynamicDataSource> selectByExample(TtDynamicDataSourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    TtDynamicDataSource selectByPrimaryKey(String dbsName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") TtDynamicDataSource record, @Param("example") TtDynamicDataSourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExample(@Param("record") TtDynamicDataSource record, @Param("example") TtDynamicDataSourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKeySelective(TtDynamicDataSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_DYNAMIC_DATA_SOURCE
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKey(TtDynamicDataSource record);
}