package com.llsfw.generator.mapper.standard.system;

import com.llsfw.generator.model.standard.system.TtOnlineSessionHis;
import com.llsfw.generator.model.standard.system.TtOnlineSessionHisCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtOnlineSessionHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int countByExample(TtOnlineSessionHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int deleteByExample(TtOnlineSessionHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int insert(TtOnlineSessionHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int insertSelective(TtOnlineSessionHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    List<TtOnlineSessionHis> selectByExample(TtOnlineSessionHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    TtOnlineSessionHis selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") TtOnlineSessionHis record, @Param("example") TtOnlineSessionHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByExample(@Param("record") TtOnlineSessionHis record, @Param("example") TtOnlineSessionHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByPrimaryKeySelective(TtOnlineSessionHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_ONLINE_SESSION_HIS
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByPrimaryKey(TtOnlineSessionHis record);
}