package com.llsfw.generator.mapper.standard.system;

import com.llsfw.generator.model.standard.system.TtRequestResponseLog;
import com.llsfw.generator.model.standard.system.TtRequestResponseLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtRequestResponseLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int countByExample(TtRequestResponseLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int deleteByExample(TtRequestResponseLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int deleteByPrimaryKey(String requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int insert(TtRequestResponseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int insertSelective(TtRequestResponseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    List<TtRequestResponseLog> selectByExample(TtRequestResponseLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    TtRequestResponseLog selectByPrimaryKey(String requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") TtRequestResponseLog record, @Param("example") TtRequestResponseLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByExample(@Param("record") TtRequestResponseLog record, @Param("example") TtRequestResponseLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByPrimaryKeySelective(TtRequestResponseLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_REQUEST_RESPONSE_LOG
     *
     * @mbggenerated Fri Jan 15 16:04:44 CST 2016
     */
    int updateByPrimaryKey(TtRequestResponseLog record);
}