package com.llsfw.generator.mapper.standard.system;

import com.llsfw.generator.model.standard.system.TtScheduledTriggerLog;
import com.llsfw.generator.model.standard.system.TtScheduledTriggerLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtScheduledTriggerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int countByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insert(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insertSelective(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    List<TtScheduledTriggerLog> selectByExample(TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    TtScheduledTriggerLog selectByPrimaryKey(String logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") TtScheduledTriggerLog record, @Param("example") TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExample(@Param("record") TtScheduledTriggerLog record, @Param("example") TtScheduledTriggerLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKeySelective(TtScheduledTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SCHEDULED_TRIGGER_LOG
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKey(TtScheduledTriggerLog record);
}