package com.llsfw.generator.mapper.standard.system;

import com.llsfw.generator.model.standard.system.TtServerGlobalParameters;
import com.llsfw.generator.model.standard.system.TtServerGlobalParametersCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtServerGlobalParametersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int countByExample(TtServerGlobalParametersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByExample(TtServerGlobalParametersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int deleteByPrimaryKey(String parametersCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insert(TtServerGlobalParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int insertSelective(TtServerGlobalParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    List<TtServerGlobalParameters> selectByExample(TtServerGlobalParametersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    TtServerGlobalParameters selectByPrimaryKey(String parametersCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") TtServerGlobalParameters record, @Param("example") TtServerGlobalParametersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByExample(@Param("record") TtServerGlobalParameters record, @Param("example") TtServerGlobalParametersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKeySelective(TtServerGlobalParameters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_SERVER_GLOBAL_PARAMETERS
     *
     * @mbggenerated Mon Dec 07 22:45:14 CST 2015
     */
    int updateByPrimaryKey(TtServerGlobalParameters record);
}