package com.llsfw.webgen.model.standard.permissions;

import java.io.Serializable;
import java.util.Date;

public class TsApplicationUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.SALT
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userMPhome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_APPLICATION_USER.LAST_LOGINTIME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    private Date lastLogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.LOGIN_NAME
     *
     * @return the value of TS_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.LOGIN_NAME
     *
     * @param loginName the value for TS_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_ID
     *
     * @return the value of TS_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_ID
     *
     * @param userId the value for TS_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @return the value of TS_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @param loginPassword the value for TS_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.SALT
     *
     * @return the value of TS_APPLICATION_USER.SALT
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.SALT
     *
     * @param salt the value for TS_APPLICATION_USER.SALT
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_NAME
     *
     * @return the value of TS_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_NAME
     *
     * @param userName the value for TS_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_PHONE
     *
     * @return the value of TS_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_PHONE
     *
     * @param userPhone the value for TS_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_M_PHOME
     *
     * @return the value of TS_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserMPhome() {
        return userMPhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_M_PHOME
     *
     * @param userMPhome the value for TS_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserMPhome(String userMPhome) {
        this.userMPhome = userMPhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_EMAIL
     *
     * @return the value of TS_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_EMAIL
     *
     * @param userEmail the value for TS_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.USER_STATUS
     *
     * @return the value of TS_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.USER_STATUS
     *
     * @param userStatus the value for TS_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.CREATE_BY
     *
     * @return the value of TS_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.CREATE_BY
     *
     * @param createBy the value for TS_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.CREATE_DATE
     *
     * @return the value of TS_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.CREATE_DATE
     *
     * @param createDate the value for TS_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.UPDATE_BY
     *
     * @return the value of TS_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.UPDATE_BY
     *
     * @param updateBy the value for TS_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.UPDATE_DATE
     *
     * @return the value of TS_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.UPDATE_DATE
     *
     * @param updateDate the value for TS_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_APPLICATION_USER.LAST_LOGINTIME
     *
     * @return the value of TS_APPLICATION_USER.LAST_LOGINTIME
     *
     * @mbggenerated Tue Mar 08 12:54:04 CST 2016
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_APPLICATION_USER.LAST_LOGINTIME
     *
     * @param lastLogintime the value for TS_APPLICATION_USER.LAST_LOGINTIME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TsApplicationUser other = (TsApplicationUser) that;
        return (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLoginPassword() == null ? other.getLoginPassword() == null : this.getLoginPassword().equals(other.getLoginPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getUserMPhome() == null ? other.getUserMPhome() == null : this.getUserMPhome().equals(other.getUserMPhome()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getLastLogintime() == null ? other.getLastLogintime() == null : this.getLastLogintime().equals(other.getLastLogintime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLoginPassword() == null) ? 0 : getLoginPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUserMPhome() == null) ? 0 : getUserMPhome().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getLastLogintime() == null) ? 0 : getLastLogintime().hashCode());
        return result;
    }
}