package com.llsfw.webgen.model.standard.permissions;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TsFunctionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public TsFunctionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFunctionCodeIsNull() {
            addCriterion("FUNCTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeIsNotNull() {
            addCriterion("FUNCTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeEqualTo(String value) {
            addCriterion("FUNCTION_CODE =", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotEqualTo(String value) {
            addCriterion("FUNCTION_CODE <>", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeGreaterThan(String value) {
            addCriterion("FUNCTION_CODE >", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_CODE >=", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLessThan(String value) {
            addCriterion("FUNCTION_CODE <", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_CODE <=", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLike(String value) {
            addCriterion("FUNCTION_CODE like", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotLike(String value) {
            addCriterion("FUNCTION_CODE not like", value, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeIn(List<String> values) {
            addCriterion("FUNCTION_CODE in", values, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotIn(List<String> values) {
            addCriterion("FUNCTION_CODE not in", values, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeBetween(String value1, String value2) {
            addCriterion("FUNCTION_CODE between", value1, value2, "functionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_CODE not between", value1, value2, "functionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeIsNull() {
            addCriterion("PARENT_FUNCTION_CODE is null");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeIsNotNull() {
            addCriterion("PARENT_FUNCTION_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeEqualTo(String value) {
            addCriterion("PARENT_FUNCTION_CODE =", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeNotEqualTo(String value) {
            addCriterion("PARENT_FUNCTION_CODE <>", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeGreaterThan(String value) {
            addCriterion("PARENT_FUNCTION_CODE >", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_FUNCTION_CODE >=", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeLessThan(String value) {
            addCriterion("PARENT_FUNCTION_CODE <", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeLessThanOrEqualTo(String value) {
            addCriterion("PARENT_FUNCTION_CODE <=", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeLike(String value) {
            addCriterion("PARENT_FUNCTION_CODE like", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeNotLike(String value) {
            addCriterion("PARENT_FUNCTION_CODE not like", value, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeIn(List<String> values) {
            addCriterion("PARENT_FUNCTION_CODE in", values, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeNotIn(List<String> values) {
            addCriterion("PARENT_FUNCTION_CODE not in", values, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeBetween(String value1, String value2) {
            addCriterion("PARENT_FUNCTION_CODE between", value1, value2, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeNotBetween(String value1, String value2) {
            addCriterion("PARENT_FUNCTION_CODE not between", value1, value2, "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNull() {
            addCriterion("FUNCTION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIsNotNull() {
            addCriterion("FUNCTION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionNameEqualTo(String value) {
            addCriterion("FUNCTION_NAME =", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotEqualTo(String value) {
            addCriterion("FUNCTION_NAME <>", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThan(String value) {
            addCriterion("FUNCTION_NAME >", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameGreaterThanOrEqualTo(String value) {
            addCriterion("FUNCTION_NAME >=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThan(String value) {
            addCriterion("FUNCTION_NAME <", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLessThanOrEqualTo(String value) {
            addCriterion("FUNCTION_NAME <=", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLike(String value) {
            addCriterion("FUNCTION_NAME like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotLike(String value) {
            addCriterion("FUNCTION_NAME not like", value, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameIn(List<String> values) {
            addCriterion("FUNCTION_NAME in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotIn(List<String> values) {
            addCriterion("FUNCTION_NAME not in", values, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameBetween(String value1, String value2) {
            addCriterion("FUNCTION_NAME between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andFunctionNameNotBetween(String value1, String value2) {
            addCriterion("FUNCTION_NAME not between", value1, value2, "functionName");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelIsNull() {
            addCriterion("FUNCTION_ACCESS_CHANNEL is null");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelIsNotNull() {
            addCriterion("FUNCTION_ACCESS_CHANNEL is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelEqualTo(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL =", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelNotEqualTo(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL <>", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelGreaterThan(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL >", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelGreaterThanOrEqualTo(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL >=", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelLessThan(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL <", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelLessThanOrEqualTo(Short value) {
            addCriterion("FUNCTION_ACCESS_CHANNEL <=", value, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelIn(List<Short> values) {
            addCriterion("FUNCTION_ACCESS_CHANNEL in", values, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelNotIn(List<Short> values) {
            addCriterion("FUNCTION_ACCESS_CHANNEL not in", values, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelBetween(Short value1, Short value2) {
            addCriterion("FUNCTION_ACCESS_CHANNEL between", value1, value2, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andFunctionAccessChannelNotBetween(Short value1, Short value2) {
            addCriterion("FUNCTION_ACCESS_CHANNEL not between", value1, value2, "functionAccessChannel");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("SORT is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Integer value) {
            addCriterion("SORT =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Integer value) {
            addCriterion("SORT <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Integer value) {
            addCriterion("SORT >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SORT >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Integer value) {
            addCriterion("SORT <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Integer value) {
            addCriterion("SORT <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Integer> values) {
            addCriterion("SORT in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Integer> values) {
            addCriterion("SORT not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Integer value1, Integer value2) {
            addCriterion("SORT between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SORT not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andLevelNoIsNull() {
            addCriterion("LEVEL_NO is null");
            return (Criteria) this;
        }

        public Criteria andLevelNoIsNotNull() {
            addCriterion("LEVEL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andLevelNoEqualTo(Integer value) {
            addCriterion("LEVEL_NO =", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoNotEqualTo(Integer value) {
            addCriterion("LEVEL_NO <>", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoGreaterThan(Integer value) {
            addCriterion("LEVEL_NO >", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("LEVEL_NO >=", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoLessThan(Integer value) {
            addCriterion("LEVEL_NO <", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoLessThanOrEqualTo(Integer value) {
            addCriterion("LEVEL_NO <=", value, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoIn(List<Integer> values) {
            addCriterion("LEVEL_NO in", values, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoNotIn(List<Integer> values) {
            addCriterion("LEVEL_NO not in", values, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoBetween(Integer value1, Integer value2) {
            addCriterion("LEVEL_NO between", value1, value2, "levelNo");
            return (Criteria) this;
        }

        public Criteria andLevelNoNotBetween(Integer value1, Integer value2) {
            addCriterion("LEVEL_NO not between", value1, value2, "levelNo");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("ICON is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("ICON is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("ICON =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("ICON <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("ICON >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("ICON >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("ICON <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("ICON <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("ICON like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("ICON not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("ICON in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("ICON not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("ICON between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("ICON not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNull() {
            addCriterion("REQUEST_URL is null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNotNull() {
            addCriterion("REQUEST_URL is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlEqualTo(String value) {
            addCriterion("REQUEST_URL =", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotEqualTo(String value) {
            addCriterion("REQUEST_URL <>", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThan(String value) {
            addCriterion("REQUEST_URL >", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_URL >=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThan(String value) {
            addCriterion("REQUEST_URL <", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_URL <=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLike(String value) {
            addCriterion("REQUEST_URL like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotLike(String value) {
            addCriterion("REQUEST_URL not like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIn(List<String> values) {
            addCriterion("REQUEST_URL in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotIn(List<String> values) {
            addCriterion("REQUEST_URL not in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlBetween(String value1, String value2) {
            addCriterion("REQUEST_URL between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotBetween(String value1, String value2) {
            addCriterion("REQUEST_URL not between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlIsNull() {
            addCriterion("REQUEST_REMARK_URL is null");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlIsNotNull() {
            addCriterion("REQUEST_REMARK_URL is not null");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlEqualTo(String value) {
            addCriterion("REQUEST_REMARK_URL =", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlNotEqualTo(String value) {
            addCriterion("REQUEST_REMARK_URL <>", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlGreaterThan(String value) {
            addCriterion("REQUEST_REMARK_URL >", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_REMARK_URL >=", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlLessThan(String value) {
            addCriterion("REQUEST_REMARK_URL <", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_REMARK_URL <=", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlLike(String value) {
            addCriterion("REQUEST_REMARK_URL like", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlNotLike(String value) {
            addCriterion("REQUEST_REMARK_URL not like", value, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlIn(List<String> values) {
            addCriterion("REQUEST_REMARK_URL in", values, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlNotIn(List<String> values) {
            addCriterion("REQUEST_REMARK_URL not in", values, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlBetween(String value1, String value2) {
            addCriterion("REQUEST_REMARK_URL between", value1, value2, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlNotBetween(String value1, String value2) {
            addCriterion("REQUEST_REMARK_URL not between", value1, value2, "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andRequestTargetIsNull() {
            addCriterion("REQUEST_TARGET is null");
            return (Criteria) this;
        }

        public Criteria andRequestTargetIsNotNull() {
            addCriterion("REQUEST_TARGET is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTargetEqualTo(Short value) {
            addCriterion("REQUEST_TARGET =", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetNotEqualTo(Short value) {
            addCriterion("REQUEST_TARGET <>", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetGreaterThan(Short value) {
            addCriterion("REQUEST_TARGET >", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetGreaterThanOrEqualTo(Short value) {
            addCriterion("REQUEST_TARGET >=", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetLessThan(Short value) {
            addCriterion("REQUEST_TARGET <", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetLessThanOrEqualTo(Short value) {
            addCriterion("REQUEST_TARGET <=", value, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetIn(List<Short> values) {
            addCriterion("REQUEST_TARGET in", values, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetNotIn(List<Short> values) {
            addCriterion("REQUEST_TARGET not in", values, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetBetween(Short value1, Short value2) {
            addCriterion("REQUEST_TARGET between", value1, value2, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andRequestTargetNotBetween(Short value1, Short value2) {
            addCriterion("REQUEST_TARGET not between", value1, value2, "requestTarget");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andFunctionCodeLikeInsensitive(String value) {
            addCriterion("upper(FUNCTION_CODE) like", value.toUpperCase(), "functionCode");
            return (Criteria) this;
        }

        public Criteria andParentFunctionCodeLikeInsensitive(String value) {
            addCriterion("upper(PARENT_FUNCTION_CODE) like", value.toUpperCase(), "parentFunctionCode");
            return (Criteria) this;
        }

        public Criteria andFunctionNameLikeInsensitive(String value) {
            addCriterion("upper(FUNCTION_NAME) like", value.toUpperCase(), "functionName");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andIconLikeInsensitive(String value) {
            addCriterion("upper(ICON) like", value.toUpperCase(), "icon");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLikeInsensitive(String value) {
            addCriterion("upper(REQUEST_URL) like", value.toUpperCase(), "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestRemarkUrlLikeInsensitive(String value) {
            addCriterion("upper(REQUEST_REMARK_URL) like", value.toUpperCase(), "requestRemarkUrl");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 08 12:54:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}