package com.llsfw.webgen.model.standard.permissions;

import java.io.Serializable;
import java.util.Date;

public class TsFunction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String functionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.PARENT_FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String parentFunctionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.FUNCTION_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.FUNCTION_ACCESS_CHANNEL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Short functionAccessChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.LEVEL_NO
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Integer levelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.ICON
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.REQUEST_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.REQUEST_REMARK_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String requestRemarkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.REQUEST_TARGET
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Short requestTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_FUNCTION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.FUNCTION_CODE
     *
     * @return the value of TS_FUNCTION.FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.FUNCTION_CODE
     *
     * @param functionCode the value for TS_FUNCTION.FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.PARENT_FUNCTION_CODE
     *
     * @return the value of TS_FUNCTION.PARENT_FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getParentFunctionCode() {
        return parentFunctionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.PARENT_FUNCTION_CODE
     *
     * @param parentFunctionCode the value for TS_FUNCTION.PARENT_FUNCTION_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setParentFunctionCode(String parentFunctionCode) {
        this.parentFunctionCode = parentFunctionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.FUNCTION_NAME
     *
     * @return the value of TS_FUNCTION.FUNCTION_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.FUNCTION_NAME
     *
     * @param functionName the value for TS_FUNCTION.FUNCTION_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.STATUS
     *
     * @return the value of TS_FUNCTION.STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.STATUS
     *
     * @param status the value for TS_FUNCTION.STATUS
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.FUNCTION_ACCESS_CHANNEL
     *
     * @return the value of TS_FUNCTION.FUNCTION_ACCESS_CHANNEL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Short getFunctionAccessChannel() {
        return functionAccessChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.FUNCTION_ACCESS_CHANNEL
     *
     * @param functionAccessChannel the value for TS_FUNCTION.FUNCTION_ACCESS_CHANNEL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setFunctionAccessChannel(Short functionAccessChannel) {
        this.functionAccessChannel = functionAccessChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.SORT
     *
     * @return the value of TS_FUNCTION.SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.SORT
     *
     * @param sort the value for TS_FUNCTION.SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.LEVEL_NO
     *
     * @return the value of TS_FUNCTION.LEVEL_NO
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Integer getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.LEVEL_NO
     *
     * @param levelNo the value for TS_FUNCTION.LEVEL_NO
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setLevelNo(Integer levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.ICON
     *
     * @return the value of TS_FUNCTION.ICON
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.ICON
     *
     * @param icon the value for TS_FUNCTION.ICON
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.REQUEST_URL
     *
     * @return the value of TS_FUNCTION.REQUEST_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.REQUEST_URL
     *
     * @param requestUrl the value for TS_FUNCTION.REQUEST_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.REQUEST_REMARK_URL
     *
     * @return the value of TS_FUNCTION.REQUEST_REMARK_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getRequestRemarkUrl() {
        return requestRemarkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.REQUEST_REMARK_URL
     *
     * @param requestRemarkUrl the value for TS_FUNCTION.REQUEST_REMARK_URL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setRequestRemarkUrl(String requestRemarkUrl) {
        this.requestRemarkUrl = requestRemarkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.REQUEST_TARGET
     *
     * @return the value of TS_FUNCTION.REQUEST_TARGET
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Short getRequestTarget() {
        return requestTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.REQUEST_TARGET
     *
     * @param requestTarget the value for TS_FUNCTION.REQUEST_TARGET
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setRequestTarget(Short requestTarget) {
        this.requestTarget = requestTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.CREATE_BY
     *
     * @return the value of TS_FUNCTION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.CREATE_BY
     *
     * @param createBy the value for TS_FUNCTION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.CREATE_DATE
     *
     * @return the value of TS_FUNCTION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.CREATE_DATE
     *
     * @param createDate the value for TS_FUNCTION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.UPDATE_BY
     *
     * @return the value of TS_FUNCTION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.UPDATE_BY
     *
     * @param updateBy the value for TS_FUNCTION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_FUNCTION.UPDATE_DATE
     *
     * @return the value of TS_FUNCTION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_FUNCTION.UPDATE_DATE
     *
     * @param updateDate the value for TS_FUNCTION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TsFunction other = (TsFunction) that;
        return (this.getFunctionCode() == null ? other.getFunctionCode() == null : this.getFunctionCode().equals(other.getFunctionCode()))
            && (this.getParentFunctionCode() == null ? other.getParentFunctionCode() == null : this.getParentFunctionCode().equals(other.getParentFunctionCode()))
            && (this.getFunctionName() == null ? other.getFunctionName() == null : this.getFunctionName().equals(other.getFunctionName()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getFunctionAccessChannel() == null ? other.getFunctionAccessChannel() == null : this.getFunctionAccessChannel().equals(other.getFunctionAccessChannel()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getLevelNo() == null ? other.getLevelNo() == null : this.getLevelNo().equals(other.getLevelNo()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getRequestUrl() == null ? other.getRequestUrl() == null : this.getRequestUrl().equals(other.getRequestUrl()))
            && (this.getRequestRemarkUrl() == null ? other.getRequestRemarkUrl() == null : this.getRequestRemarkUrl().equals(other.getRequestRemarkUrl()))
            && (this.getRequestTarget() == null ? other.getRequestTarget() == null : this.getRequestTarget().equals(other.getRequestTarget()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFunctionCode() == null) ? 0 : getFunctionCode().hashCode());
        result = prime * result + ((getParentFunctionCode() == null) ? 0 : getParentFunctionCode().hashCode());
        result = prime * result + ((getFunctionName() == null) ? 0 : getFunctionName().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getFunctionAccessChannel() == null) ? 0 : getFunctionAccessChannel().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getLevelNo() == null) ? 0 : getLevelNo().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getRequestUrl() == null) ? 0 : getRequestUrl().hashCode());
        result = prime * result + ((getRequestRemarkUrl() == null) ? 0 : getRequestRemarkUrl().hashCode());
        result = prime * result + ((getRequestTarget() == null) ? 0 : getRequestTarget().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}