package com.llsfw.webgen.model.standard.permissions;

import java.io.Serializable;
import java.util.Date;

public class TsOrganization implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.PARENT_ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String parentOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.ORG_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String orgSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_ORGANIZATION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.ORG_CODE
     *
     * @return the value of TS_ORGANIZATION.ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.ORG_CODE
     *
     * @param orgCode the value for TS_ORGANIZATION.ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.ORG_NAME
     *
     * @return the value of TS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.ORG_NAME
     *
     * @param orgName the value for TS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.PARENT_ORG_CODE
     *
     * @return the value of TS_ORGANIZATION.PARENT_ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getParentOrgCode() {
        return parentOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.PARENT_ORG_CODE
     *
     * @param parentOrgCode the value for TS_ORGANIZATION.PARENT_ORG_CODE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setParentOrgCode(String parentOrgCode) {
        this.parentOrgCode = parentOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.ORG_SORT
     *
     * @return the value of TS_ORGANIZATION.ORG_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getOrgSort() {
        return orgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.ORG_SORT
     *
     * @param orgSort the value for TS_ORGANIZATION.ORG_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setOrgSort(String orgSort) {
        this.orgSort = orgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.CREATE_BY
     *
     * @return the value of TS_ORGANIZATION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.CREATE_BY
     *
     * @param createBy the value for TS_ORGANIZATION.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.CREATE_DATE
     *
     * @return the value of TS_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.CREATE_DATE
     *
     * @param createDate the value for TS_ORGANIZATION.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.UPDATE_BY
     *
     * @return the value of TS_ORGANIZATION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.UPDATE_BY
     *
     * @param updateBy the value for TS_ORGANIZATION.UPDATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ORGANIZATION.UPDATE_DATE
     *
     * @return the value of TS_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ORGANIZATION.UPDATE_DATE
     *
     * @param updateDate the value for TS_ORGANIZATION.UPDATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ORGANIZATION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TsOrganization other = (TsOrganization) that;
        return (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getParentOrgCode() == null ? other.getParentOrgCode() == null : this.getParentOrgCode().equals(other.getParentOrgCode()))
            && (this.getOrgSort() == null ? other.getOrgSort() == null : this.getOrgSort().equals(other.getOrgSort()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ORGANIZATION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getParentOrgCode() == null) ? 0 : getParentOrgCode().hashCode());
        result = prime * result + ((getOrgSort() == null) ? 0 : getOrgSort().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}