package com.llsfw.webgen.model.standard.permissions;

import java.io.Serializable;
import java.util.Date;

public class TsUserPortal extends TsUserPortalKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_USER_PORTAL.PORTAL_INDEX
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Short portalIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_USER_PORTAL.PORTAL_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Integer portalSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_USER_PORTAL.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_USER_PORTAL.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_USER_PORTAL.PORTAL_INDEX
     *
     * @return the value of TS_USER_PORTAL.PORTAL_INDEX
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Short getPortalIndex() {
        return portalIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_USER_PORTAL.PORTAL_INDEX
     *
     * @param portalIndex the value for TS_USER_PORTAL.PORTAL_INDEX
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setPortalIndex(Short portalIndex) {
        this.portalIndex = portalIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_USER_PORTAL.PORTAL_SORT
     *
     * @return the value of TS_USER_PORTAL.PORTAL_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Integer getPortalSort() {
        return portalSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_USER_PORTAL.PORTAL_SORT
     *
     * @param portalSort the value for TS_USER_PORTAL.PORTAL_SORT
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setPortalSort(Integer portalSort) {
        this.portalSort = portalSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_USER_PORTAL.CREATE_BY
     *
     * @return the value of TS_USER_PORTAL.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_USER_PORTAL.CREATE_BY
     *
     * @param createBy the value for TS_USER_PORTAL.CREATE_BY
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_USER_PORTAL.CREATE_DATE
     *
     * @return the value of TS_USER_PORTAL.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_USER_PORTAL.CREATE_DATE
     *
     * @param createDate the value for TS_USER_PORTAL.CREATE_DATE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TsUserPortal other = (TsUserPortal) that;
        return (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getPortalCode() == null ? other.getPortalCode() == null : this.getPortalCode().equals(other.getPortalCode()))
            && (this.getPortalIndex() == null ? other.getPortalIndex() == null : this.getPortalIndex().equals(other.getPortalIndex()))
            && (this.getPortalSort() == null ? other.getPortalSort() == null : this.getPortalSort().equals(other.getPortalSort()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getPortalCode() == null) ? 0 : getPortalCode().hashCode());
        result = prime * result + ((getPortalIndex() == null) ? 0 : getPortalIndex().hashCode());
        result = prime * result + ((getPortalSort() == null) ? 0 : getPortalSort().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }
}