package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsApplicationUser;
import com.llsfw.webgen.model.standard.permissions.TsApplicationUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsApplicationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsApplicationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsApplicationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsApplicationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsApplicationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsApplicationUser> selectByExample(TsApplicationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsApplicationUser selectByPrimaryKey(String loginName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsApplicationUser record, @Param("example") TsApplicationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsApplicationUser record, @Param("example") TsApplicationUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsApplicationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_APPLICATION_USER
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsApplicationUser record);
}