package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsFunction;
import com.llsfw.webgen.model.standard.permissions.TsFunctionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsFunction> selectByExample(TsFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsFunction selectByPrimaryKey(String functionCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsFunction record, @Param("example") TsFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsFunction record, @Param("example") TsFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsFunction record);
}