package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsJob;
import com.llsfw.webgen.model.standard.permissions.TsJobCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(String jobCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsJob> selectByExample(TsJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsJob selectByPrimaryKey(String jobCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsJob record, @Param("example") TsJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsJob record, @Param("example") TsJobCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsJob record);
}