package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsJobRole;
import com.llsfw.webgen.model.standard.permissions.TsJobRoleCriteria;
import com.llsfw.webgen.model.standard.permissions.TsJobRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsJobRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsJobRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsJobRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(TsJobRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsJobRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsJobRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsJobRole> selectByExample(TsJobRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsJobRole selectByPrimaryKey(TsJobRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsJobRole record, @Param("example") TsJobRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsJobRole record, @Param("example") TsJobRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsJobRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_JOB_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsJobRole record);
}