package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsPortal;
import com.llsfw.webgen.model.standard.permissions.TsPortalCriteria;
import com.llsfw.webgen.model.standard.permissions.TsPortalKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsPortalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(TsPortalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsPortal> selectByExample(TsPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsPortal selectByPrimaryKey(TsPortalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsPortal record, @Param("example") TsPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsPortal record, @Param("example") TsPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsPortal record);
}