package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsRoleFunction;
import com.llsfw.webgen.model.standard.permissions.TsRoleFunctionCriteria;
import com.llsfw.webgen.model.standard.permissions.TsRoleFunctionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsRoleFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsRoleFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsRoleFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(TsRoleFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsRoleFunction> selectByExample(TsRoleFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsRoleFunction selectByPrimaryKey(TsRoleFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsRoleFunction record, @Param("example") TsRoleFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsRoleFunction record, @Param("example") TsRoleFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsRoleFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsRoleFunction record);
}