package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsRole;
import com.llsfw.webgen.model.standard.permissions.TsRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsRole> selectByExample(TsRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsRole selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsRole record, @Param("example") TsRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsRole record, @Param("example") TsRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ROLE
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsRole record);
}