package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsUserFunction;
import com.llsfw.webgen.model.standard.permissions.TsUserFunctionCriteria;
import com.llsfw.webgen.model.standard.permissions.TsUserFunctionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsUserFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsUserFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsUserFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(TsUserFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsUserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsUserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsUserFunction> selectByExample(TsUserFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsUserFunction selectByPrimaryKey(TsUserFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsUserFunction record, @Param("example") TsUserFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsUserFunction record, @Param("example") TsUserFunctionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsUserFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_FUNCTION
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsUserFunction record);
}