package com.llsfw.webgen.mapper.standard.permissions;

import com.llsfw.webgen.model.standard.permissions.TsUserPortal;
import com.llsfw.webgen.model.standard.permissions.TsUserPortalCriteria;
import com.llsfw.webgen.model.standard.permissions.TsUserPortalKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsUserPortalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int countByExample(TsUserPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByExample(TsUserPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int deleteByPrimaryKey(TsUserPortalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insert(TsUserPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int insertSelective(TsUserPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    List<TsUserPortal> selectByExample(TsUserPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    TsUserPortal selectByPrimaryKey(TsUserPortalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") TsUserPortal record, @Param("example") TsUserPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByExample(@Param("record") TsUserPortal record, @Param("example") TsUserPortalCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKeySelective(TsUserPortal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_USER_PORTAL
     *
     * @mbggenerated Tue Mar 08 12:54:05 CST 2016
     */
    int updateByPrimaryKey(TsUserPortal record);
}